services:
  cqlsh-setup:
    image: nuvo/docker-cqlsh
    container_name: cqlsh-setup
    environment:
      - CQLSH_HOST=34.116.241.217
      - CQLSH_PORT=9042
      - CQLVERSION=3.4.6
    volumes:
      - ./setup:/scripts
